import { TotoRequest } from "../../model/TotoRequest";

/**
 * Model for the message to agent as part of a conversation.
 */
export interface AgentConversationMessage extends TotoRequest {
    conversationId: string;     // ID of the conversation to which the message belongs (if it's a new conversation, this can be generated by the server and returned in the response)
    messageId: string;          // ID of the message (can be generated by the client or the server)
    actor: "user" | "agent";
    agentId: string;            // ID of the agent this message is directed to
    message: string;            // The user message content
    extras?: {
        subjectEmail?: string;     // Email of the user subject of the interactions (useful for personalization or follow-up)
    }
}